# Generated by Django 6.0 on 2026-02-07 15:50

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeding",
            name="amount_oz",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.1")),
                    django.core.validators.MaxValueValidator(Decimal("50")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feeding",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
    ]
