# Generated by Django 6.0 on 2026-02-10 16:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_shareinvite_childshare'),
        ('feedings', '0003_alter_feeding_fed_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feeding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_oz__isnull', False), ('duration_minutes__isnull', True), ('feeding_type', 'bottle'), ('side__exact', '')), ('feeding_type', 'breast'), _connector='OR'), name='bottle_has_amount_oz'),
        ),
        migrations.AddConstraint(
            model_name='feeding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_oz__isnull', True), ('duration_minutes__isnull', False), ('feeding_type', 'breast'), ('side__in', ['left', 'right', 'both'])), ('feeding_type', 'bottle'), _connector='OR'), name='breast_has_duration_and_side'),
        ),
        migrations.AddConstraint(
            model_name='feeding',
            constraint=models.CheckConstraint(condition=models.Q(('amount_oz__isnull', True), models.Q(('amount_oz__gte', Decimal('0.1')), ('amount_oz__lte', Decimal('50'))), _connector='OR'), name='bottle_amount_in_range'),
        ),
        migrations.AddConstraint(
            model_name='feeding',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 180)), _connector='OR'), name='breast_duration_in_range'),
        ),
    ]
