# Generated by Django 6.0 on 2026-02-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0010_child_feeding_reminder_interval"),
        ("feedings", "0004_feeding_bottle_has_amount_oz_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feeding",
            index=models.Index(
                fields=["child", "fed_at"], name="children_fe_child_i_69e6cf_idx"
            ),
        ),
    ]
