# Generated by Django 6.0 on 2026-02-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nap',
            name='napped_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
