# Generated by Django 6.0 on 2026-02-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0010_child_feeding_reminder_interval"),
        ("naps", "0003_nap_ended_at_nap_nap_ended_after_start"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="nap",
            index=models.Index(
                fields=["child", "napped_at"], name="children_na_child_i_fa7766_idx"
            ),
        ),
    ]
