# Generated by Django 6.0 on 2026-03-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone identifier (e.g. America/New_York). No DB index by design; add one if timezone-based queries are introduced.",
                max_length=63,
            ),
        ),
    ]
