# Generated by Django 6.0 on 2026-02-01 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0002_diaperchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("napped_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naps",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-napped_at"],
            },
        ),
    ]
