# Generated by Django 6.0 on 2026-02-10 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_shareinvite_childshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['parent', '-date_of_birth'], name='children_ch_parent__595e58_idx'),
        ),
    ]
