# Generated by Django 6.0 on 2026-02-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0007_child_children_ch_parent__595e58_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childshare",
            name="role",
            field=models.CharField(
                choices=[("CO", "Co-parent"), ("CG", "Caregiver")],
                db_index=True,
                default="CG",
                max_length=2,
            ),
        ),
    ]
