# Generated by Django 6.0 on 2026-02-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0009_child_custom_bottle_high_oz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="feeding_reminder_interval",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (2, "2 hours"),
                    (3, "3 hours"),
                    (4, "4 hours"),
                    (6, "6 hours"),
                ],
                default=None,
                help_text="Interval (hours) for feeding reminders; null = disabled",
                null=True,
            ),
        ),
    ]
