# Generated by Django 6.0 on 2026-02-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diapers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaperchange",
            name="changed_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
