# Generated by Django 6.0 on 2026-02-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0010_child_feeding_reminder_interval"),
        ("diapers", "0002_alter_diaperchange_changed_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="diaperchange",
            index=models.Index(
                fields=["child", "changed_at"], name="children_di_child_i_c366c0_idx"
            ),
        ),
    ]
