# Generated by Django 6.0 on 2026-02-27 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0010_child_feeding_reminder_interval"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("feeding", "Feeding"),
                    ("diaper", "Diaper Change"),
                    ("nap", "Nap"),
                    ("feeding_reminder", "Feeding Reminder"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FeedingReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "window_start",
                    models.DateTimeField(
                        help_text="Start of the reminder window (last_feeding.fed_at)"
                    ),
                ),
                (
                    "reminder_number",
                    models.PositiveIntegerField(
                        choices=[(1, "Initial"), (2, "Repeat")],
                        help_text="Which reminder in this window (1=initial at interval, 2=repeat at 1.5x interval)",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeding_reminder_logs",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["child", "window_start", "reminder_number"],
                        name="feed_remind_log_idx",
                    ),
                    models.Index(fields=["sent_at"], name="feed_remind_clean_idx"),
                ],
                "unique_together": {("child", "window_start", "reminder_number")},
            },
        ),
    ]
