# Generated by Django 6.0 on 2026-03-08 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0011_alter_child_custom_bottle_high_oz_and_more"),
        ("notifications", "0002_alter_notification_actor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("feeding", "Feeding"),
                    ("diaper", "Diaper Change"),
                    ("nap", "Nap"),
                    ("feeding_reminder", "Feeding Reminder"),
                    ("pattern_alert", "Pattern Alert"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("android", "Android"),
                            ("ios", "iOS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="devtoken_user_active_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PatternAlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        help_text="Type of pattern alert: 'feeding' or 'nap'",
                        max_length=20,
                    ),
                ),
                (
                    "window_start",
                    models.DateTimeField(
                        help_text="Timestamp of the last event when this alert fired"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_alert_logs",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["child", "alert_type", "window_start"],
                        name="pattern_alert_log_idx",
                    ),
                    models.Index(fields=["sent_at"], name="pattern_alert_clean_idx"),
                ],
                "unique_together": {("child", "alert_type", "window_start")},
            },
        ),
    ]
