# Generated by Django 6.0 on 2026-03-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_add_device_token_and_pattern_alert_log"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="patternalertlog",
            name="pattern_alert_log_idx",
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="patternalertlog",
            name="alert_type",
            field=models.CharField(
                choices=[("feeding", "Feeding"), ("nap", "Nap")], max_length=20
            ),
        ),
    ]
