"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.management.utils import get_random_secret_key

# =============================================================================
# Path Configuration
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# Environment Variables Helper
# =============================================================================


def env_bool(name: str, default: bool = False) -> bool:
    """Get boolean environment variable."""
    return os.environ.get(name, str(default)).lower() in ("true", "1", "yes")


def env_list(name: str, default: str = "") -> list[str]:
    """Get comma-separated list from environment variable."""
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# =============================================================================
# Core Settings
# =============================================================================

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", get_random_secret_key())
DEBUG = env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = (
    ["*"] if DEBUG else env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
)

ROOT_URLCONF = "django_project.urls"
WSGI_APPLICATION = "django_project.wsgi.application"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.CustomUser"

# =============================================================================
# Installed Applications
# =============================================================================

INSTALLED_APPS = [
    # Django built-in apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Third-party apps
    "allauth",
    "allauth.account",
    "allauth.headless",
    "corsheaders",
    "crispy_forms",
    "crispy_bootstrap5",
    "rest_framework",
    "rest_framework.authtoken",
    "celery",
    # Local apps
    "accounts",
    "analytics",
    "children",
    "diapers",
    "feedings",
    "naps",
    "notifications",
    "pages",
]

# =============================================================================
# Middleware
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Must be before CsrfViewMiddleware
    "django_project.middleware.CSRFExemptMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    # Disable browser caching of API responses (prevent stale data)
    "django_project.middleware.NoCacheAPIMiddleware",
]

# =============================================================================
# Templates
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "children.context_processors.user_timezone",
            ],
        },
    },
]

# =============================================================================
# Database Configuration
# =============================================================================


def _get_database_config():
    """Get database configuration based on environment.

    Includes connection pooling and health checks for production stability.
    """
    # Connection lifetime: reuse connections for this many seconds
    conn_max_age = int(os.environ.get("DB_CONN_MAX_AGE", "600"))

    if os.environ.get("DATABASE_URL"):
        # Render or other cloud providers
        config = dj_database_url.config(
            conn_max_age=conn_max_age,
            conn_health_checks=True,
        )
        # Add pooling options for cloud PostgreSQL
        if config.get("ENGINE") == "django.db.backends.postgresql":
            config.setdefault("CONN_MAX_AGE", conn_max_age)
            config.setdefault("OPTIONS", {}).update(
                {
                    "connect_timeout": 10,
                    "options": "-c statement_timeout=30000",  # 30 second statement timeout
                }
            )
        return config

    elif os.environ.get("DATABASE_HOST"):
        # Docker/Podman compose setup with connection pooling
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DATABASE_NAME", "postgres"),
            "USER": os.environ.get("DATABASE_USER", "postgres"),
            "PASSWORD": os.environ.get("DATABASE_PASSWORD", ""),
            "HOST": os.environ.get("DATABASE_HOST"),
            "PORT": os.environ.get("DATABASE_PORT", "5432"),
            # Connection pooling and persistence
            "CONN_MAX_AGE": conn_max_age,
            "OPTIONS": {
                # Connection timeout (seconds)
                "connect_timeout": 10,
                # Statement timeout (milliseconds)
                "options": f"-c statement_timeout={int(conn_max_age * 1000)}",
            },
            # Enable connection pooling in psycopg2
            "ATOMIC_REQUESTS": False,  # Allow concurrent requests
        }
    else:
        # Local development with SQLite
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            # SQLite WAL mode for better concurrency
            "OPTIONS": {
                "timeout": 20,
                "isolation_level": None,  # Autocommit mode
            },
        }


DATABASES = {
    "default": _get_database_config(),
}

# =============================================================================
# Database Connection Pooling
# =============================================================================

# Connection pool configuration
# These can be overridden via environment variables:
# - DB_POOL_MIN_SIZE: Minimum connections to maintain (default: 2)
# - DB_POOL_MAX_SIZE: Maximum connections in pool (default: 10)
# - DB_CONN_MAX_AGE: Connection lifetime in seconds (default: 600 = 10 min)
#
# Production recommendations:
# - DB_POOL_MIN_SIZE=5 (more aggressive pre-warming)
# - DB_POOL_MAX_SIZE=20 (handle more concurrent requests)
# - DB_CONN_MAX_AGE=300 (shorter connection lifetime for better freshness)

# =============================================================================
# Cache Configuration (Redis)
# =============================================================================


def _get_cache_config():
    """Get cache configuration - uses Redis if available, falls back to local memory.

    Redis Configuration:
    - Default: redis://redis:6379/0 (Docker/Podman network)
    - Override via REDIS_URL environment variable
    - Uses django-redis for connection pooling and timeout handling
    """
    redis_host = os.environ.get("REDIS_HOST", "localhost")
    redis_port = os.environ.get("REDIS_PORT", "6379")
    redis_url = os.environ.get("REDIS_URL", f"redis://{redis_host}:{redis_port}/0")

    if os.environ.get("DJANGO_DEBUG"):
        # Development: Try Redis, fall back to local memory if unavailable
        return {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": redis_url,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    "CONNECTION_POOL_KWARGS": {
                        "retry_on_timeout": True,
                        "socket_connect_timeout": 5,
                        "socket_timeout": 5,
                    },
                    "SOCKET_CONNECT_TIMEOUT": 5,
                    "SOCKET_TIMEOUT": 5,
                    "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                    "IGNORE_EXCEPTIONS": True,  # Fall back to direct DB on cache miss
                },
            }
        }
    else:
        # Production: Always use Redis (fail hard if unavailable)
        return {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": redis_url,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    "CONNECTION_POOL_KWARGS": {
                        "retry_on_timeout": True,
                        "socket_connect_timeout": 10,
                        "socket_timeout": 10,
                        "max_connections": 50,
                    },
                    "SOCKET_CONNECT_TIMEOUT": 10,
                    "SOCKET_TIMEOUT": 10,
                    "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                    "IGNORE_EXCEPTIONS": False,  # Fail hard in production
                },
            }
        }


CACHES = _get_cache_config()

# Session backend: Store sessions in Redis instead of database
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# =============================================================================
# Celery Configuration
# =============================================================================

CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL",
    f"redis://{os.environ.get('REDIS_HOST', 'localhost')}:{os.environ.get('REDIS_PORT', '6379')}/0",
)
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND",
    f"redis://{os.environ.get('REDIS_HOST', 'localhost')}:{os.environ.get('REDIS_PORT', '6379')}/1",
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"  # Will use TIME_ZONE when it's defined below
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = (
    25 * 60
)  # 25 minutes soft limit (raises SoftTimeLimitExceeded)

CELERY_BEAT_SCHEDULE = {
    "cleanup-old-notifications": {
        "task": "notifications.tasks.cleanup_old_notifications",
        "schedule": 86400.0,  # Every 24 hours
    },
    "check-feeding-reminders": {
        "task": "notifications.tasks.check_feeding_reminders",
        "schedule": 1800.0,  # Every 30 minutes
    },
}

# =============================================================================
# Authentication & Authorization
# =============================================================================

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =============================================================================
# Internationalization
# =============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# =============================================================================
# Static Files
# =============================================================================

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# =============================================================================
# Email Configuration
# =============================================================================

EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

# =============================================================================
# Security Settings
# =============================================================================

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Development CORS and CSRF settings
_DEV_ORIGINS = [
    "http://localhost:4200",  # Angular dev server
    "http://127.0.0.1:4200",
    "http://localhost:3000",  # Alternative frontend port
    "http://127.0.0.1:3000",
]

CSRF_TRUSTED_ORIGINS = _DEV_ORIGINS if DEBUG else env_list("CSRF_TRUSTED_ORIGINS")

CORS_ALLOWED_ORIGINS = _DEV_ORIGINS if DEBUG else env_list("CORS_ALLOWED_ORIGINS")

CORS_ALLOW_CREDENTIALS = True

# Exempt allauth headless API from CSRF (for token-based SPA authentication)
CSRF_EXEMPT_URLS = [
    r"^api/v1/browser/v1/auth/",  # allauth headless endpoints (no leading slash)
]

# Production-only security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# =============================================================================
# Django REST Framework
# =============================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    # Rate limiting: Throttle API requests to prevent abuse and ensure stability
    # Uses user ID for authenticated users, IP address for anonymous
    # Cache backend required (in-memory by default for development)
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Authenticated users: 1000 requests per hour (allows ~16 per minute)
        # Suitable for normal app usage, aggressive automation, and testing
        "user": "1000/hour",
        # Accept invite: 20 per hour (strict, due to race conditions and transactions)
        # Relaxed when DEBUG or RELAX_E2E_THROTTLES=1 so E2E suite can run without 429s
        "accept_invite": (
            "100/hour"
            if (DEBUG or env_bool("RELAX_E2E_THROTTLES", False))
            else "20/hour"
        ),
        # Tracking creation: strict in production; relaxed when DEBUG or RELAX_E2E_THROTTLES
        # so E2E (pagination, pattern-alerts, quick-log, etc.) can create 51+ items
        "tracking_create": (
            "10000/hour"
            if (DEBUG or env_bool("RELAX_E2E_THROTTLES", False))
            else "120/hour"
        ),
    },
}

# =============================================================================
# Django-allauth Configuration
# =============================================================================

SITE_ID = 1

LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"

HEADLESS_ONLY = False  # Allow both web UI and API

HEADLESS_FRONTEND_URLS = {  # nosec B105
    "account_confirm_email": "http://localhost:4200/auth/verify-email/{key}",
    "account_reset_password": "http://localhost:4200/auth/reset-password/{key}",
    "account_reset_password_from_key": "http://localhost:4200/auth/reset-password/{key}",
    "account_signup": "http://localhost:4200/signup",
}

# =============================================================================
# Django-crispy-forms Configuration
# =============================================================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
